### ISSUE TITLE
more compact storage of timezone data?

### ISSUE THREAD

**Issue by skilchen** [treeform/chrono#1]
You might want to take a look at how the guys at http://momentjs.com/timezone/ store the timezone data in their module.

**Comment by treeform** [comment]
I have compressed timezone DST info to 0.7MB. I fee like this is still not the the 25k from moment-timezone but its much better then the 6MB before.

**Comment by treeform** [comment]
I have added a timezone fetcher and generator. Now you can ask for less timezones by limiting it per year, which will give you way less timzone data. Generating timezones from 2015 to 2025 generates only a 14k dstchanges.bin which is smaller them moment.js. This is the main reason why moment.js is small.

https://github.com/treeform/chrono/blob/master/tools/generate.nim#L18

Default time range of 1970 to 2030 generates 79k tzdata/dstchanges.bin.

**Comment by skilchen** [comment]
excellent!
