### ISSUE TITLE
Z is a shortcut for UTC not for +00:00

### ISSUE THREAD

**Issue by skilchen** [treeform/chrono#2]
Z is a shortcut for UTC. You should add it only if you know that you are dealing with a time in UTC (i.e. with a Timezone with offset 0 from utc and no daylight savings in use). 
If a Timezone has an offset of 00:00 from UTC that does not mean that this zone uses UTC.  A prominent example is Africa/Casablanca with their multiple DST transitions per year. As long as the month Ramadan overlaps with the usual DST, they switch back to WET during Ramadan and then again to WEST. I think it is not correct to output timestamps in the Timezone WET with the 'Z' appended (which implies DST is not in use, which is evidently not true for many countries using the zone WET).

**Comment by treeform** [comment]
https://github.com/treeform/chrono/commit/249333d836a893490ea5836e0d882f7cbd87f663

**Comment by treeform** [comment]
Thank you for reporting this!
