### ISSUE TITLE
Unable to parse `2020-01-12T02:00:33.387824Z`

### ISSUE THREAD

**Issue by Mythical-Forest-Collective** [treeform/chrono#7]
I'm working on a wrapper for an API in Nim, and i recieve timestamps in the ISO8601 format, but `2020-01-12T02:00:33.387824Z` raises a ValueError for some reason I don't understand, despise this site (<https://dencode.com/en/date/iso8601>) being able to parse it (even if it ignores the info, but preserving it is important for the API I am using)

**Comment by treeform** [comment]
Fixed in 0.3.1 

Note: `parseIso` and `parseIsoTs` don't support fractional seconds for performance reasons and its pretty rare. Use:

```nim
    let data = "2020-01-12T02:00:33.387824Z"
    let ts = parseTs("{year/4}-{month/2}-{day/2}T{hour/2}:{minute/2}:{second}.{secondFraction}Z", data)
    check ts.format("{year/4}-{month/2}-{day/2}T{hour/2}:{minute/2}:{second}.{secondFraction/7}Z") == data
```
